project:
  type: website

extensions:
  - r-wasm/quarto-live

website:
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Alert** - under construction - feedback is welcome sven.demaeyer@uantwerpen.be"
    type: primary
    position: above-navbar
  title: "ABAR - Zurich 2026"
  page-navigation: true
  reader-mode: true
  page-footer:
    right: "Made with a lot of ‚ù§ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By University of Antwerp, 2026"

  sidebar: 
    style: "docked"
    background: "#ADA601"
    foreground: "#FFFFFF"
    pinned: true
    search: true
    align: center
    border: false
    collapse-level: 1
    contents: 
      - text: "Welcome"
        href: index.qmd
      - text: "Prerequisites"
        href: Prerequisites/Prerequisites.qmd
      - text: "Links"
        href: Links.qmd
      - text: "About me"
        href: about.qmd
    tools: 
      - icon: github
        href: https://github.com/Sdemaeyer2/STATB_2425
        text: "Statistiek B"

lang: en

format:
  html:
    theme: [cosmo, theme.scss]
    mainfont: "Atkinson Hyperlegible"
    toc: true
    code-copy: true
    code-overflow: wrap
    
